#ifndef ESCORT_EXPAND_PROTOCOL_COMMON_H
#define ESCORT_EXPAND_PROTOCOL_COMMON_H

#define DEFAULT_LISTEN_DEST "ES_EXPAND_REQUEST"
#define DEFAULT_REPLY_DEST "ES_EXPAND_REPLY"

namespace escort_protocol
{
	enum eCommandType {
		CMD_START_TASK_REQ = 1, 
		CMD_STOP_TASK_REQ = 2,
		CMD_START_TASK_REP = 201,
		CMD_STOP_TASK_REP = 202, 
	};

	enum eErrorCode
	{
		ERROR_NO = 0,
		ERROR_DEVICE_IS_OCCUPIED = 1,
		ERROR_DEVICE_IS_INVALID = 2,
		ERROR_DEVICE_IS_OFFLINE = 3,
		ERROR_DEVICE_LIST_NOT_LOAD = 10,
		ERROR_GUARDER_IS_DUTY = 11,
		ERROR_GUARDER_IS_INVALID = 12,
		ERROR_GUARDER_ALREADY_BIND_DEVICE = 13,
		ERROR_GUARDER_ALREADY_ON_DUTY = 14,
		ERROR_GUARDER_LIST_NOT_LOAD = 20,
		ERROR_TASK_IN_WARN_SITUATION = 21,
		ERROR_TASK_NOT_EXISTS = 22,
	};


}


#endif